version: '3.8'

services:
  app:
    build: .
    environment:
      - name=value
    ports:
      - "8000:8000"
    volumes:
      - roy:/app
    networks:
      - bridge-net
      - roy-net

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - roy-net

volumes:
  roy:

networks:
  bridge-net:
    driver: bridge
  roy-net:
    name: roy-net