apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-migrate
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-migrate
  template:
    metadata:
      labels:
        app: k8s-migrate
    spec:
      containers:
      - name: migrate
        image: mokchhedul/assainmentk8s:latest
        command: ["sh", "-c"]
        args:
          - python manage.py migrate
        envFrom:
        - configMapRef:
            name: k8s-config
        - secretRef:
            name: k8s-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: django-app
  namespace: production
spec:
  type: NodePort
  selector:
    app: k8s
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 31000
