apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-assainment-deployment
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-assainment
  template:
    metadata:
      labels:
        app: k8s-assainment
    spec:
      containers:
      - name: k8s-assainment
        image: mokchhedul/assainmentk8s:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        envFrom:
          - secretRef:
              name: k8s-app-secret
          - configMapRef:
              name: k8s-app-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: django-app
  namespace: production
spec:
  type: NodePort
  selector:
    app: k8s-assainment
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 31000