apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s
  template:
    metadata:
      labels:
        app: k8s
    spec:
      containers:
      - name: k8s
        image: mokchhedul/assainmentk8s:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: k8s-config
        - secretRef:
            name: k8s-secrets
        command: ["sh", "-c", "python manage.py migrate && gunicorn rapid.wsgi:application --bind 0.0.0.0:8000"]
        volumeMounts:
          - name: db-storage
            mountPath: /app/db.sqlite3
            subPath: db.sqlite3
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-pvc
